title: BeeMesh
logo: assets/img/logo.png
description: Global scale computing for long-lasting processing and functions <p>© 2020. BeeMesh by Flavio Aiello</p>
show_downloads: true
theme: jekyll-theme-minimal
